### PR TITLE
Remove support for python 2 and 3.5

### PR DESCRIPTION
**Pull request by rikardn**

### CODE REVIEW

**Comment by rikardn** [comment]
I will probably spend time on migrating to github actions here rather than fixing these issues. Might take a while though.

**Comment by rikardn** [comment]
I'll close this for now and reopen when I have something that works.

**Comment by HaoZeke** [comment]
https://github.com/symengine/symengine.py/pull/335 includes a working setup for GHA.

**Comment by rikardn** [comment]
@HaoZeke Isn't that only for the documentation? I was thinking of building and testing symengine.py

**Comment by HaoZeke** [comment]
@rikardn yup, but I meant as a starting point. Looking at the current Travis `yml` it will probably be the addition of:
```
cd $PYTHON_SOURCE_DIR
source bin/install_travis.sh
```
to the `run` block, or adding a new step; and extending the environment matrix.

**Comment by rikardn** [comment]
Ah, ok, thanks @HaoZeke!

**Comment by HaoZeke** [comment]
Infact, looking at it now, I'm not sure why I ran the tests for the bindings before `sphinx`

**Comment by rikardn** [comment]
@HaoZeke Do you intend to develop this also for a regular build/test CI? Just so I don't step on your toes here.

**Comment by HaoZeke** [comment]
@rikardn Thanks for asking! I wasn't planning on doing that; so feel free to go ahead with finishing  the migration away from travis. :)

**Pull request closed without merging**
