### PR TITLE
Support pickling of Basic objects

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
This should be ready for a review. Failing test is a network issue.

**Review by certik — APPROVED** [review]
That looks good to me.

**Comment by rikardn** [comment]
This is super useful!

**Review by rikardn — APPROVED** [review]

**Comment by bocklund** [comment]
In pycalphad, we used to subclass sympy `Symbol` objects and later extend them with some special behaviors. When switching to SymEngine, we are finding that using the subclassed objects in expressions don't survive a round trip through `pickle` without getting clobbered and changed to `Symbol` objects.

Self-contained example:

```python
import pickle
from symengine import Add, Symbol

class StateVariable(Symbol):
    def __init__(self, name):
        super().__init__(name.upper())

    def __reduce__(self):
        return self.__class__, (self.name,)

T = StateVariable('T')

loaded_T = pickle.loads(pickle.dumps(T))
assert isinstance(loaded_T, StateVariable), f"Got type {type(loaded_T)}" # passes

loaded_Add_T = list(pickle.loads(pickle.dumps(Add(T, 1))).free_symbols)[0]
assert isinstance(loaded_Add_T, StateVariable), f"Got type {type(loaded_Add_T)}" # fails
```

```python
AssertionError                            Traceback (most recent call last)
<ipython-input-1-ff0882030409> in <module>
     15
     16 loaded_Add_T = list(pickle.loads(pickle.dumps(Add(T, 1))).free_symbols)[0]
---> 17 assert isinstance(loaded_Add_T, StateVariable), f"Got type {type(loaded_Add_T)}" # fails

AssertionError: Got type <class 'symengine.lib.symengine_wrapper.Symbol'>
```

Are there any changes here or in our code that we can make to have our subclasses survive a round trip through `pickle` in expressions?

**Comment by bocklund** [comment]
Thank you, @isuruf! The changes here and upstream in SymEngine work well and solve our problem.

**Comment by certik** [comment]
Thanks @isuruf for all the work.

Thanks @bocklund for using SymEngine. I am very happy it works for you.

**Pull request merged**
