### PR TITLE
Update SymEngine and fix build issues

### PR DESCRIPTION
**Pull request by certik**
This should hopefully work.

### CODE REVIEW

**Comment by certik** [comment]
Looks like Travis passes. Now we just need to convince Appveyor to find GMP.

**Comment by certik** [comment]
Ok, so now it fails with a legitimate error in MSVC:
```
"C:\projects\symengine-py-l1jmr\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\projects\symengine-py-l1jmr\symengine\lib\symengine_wrapper.vcxproj" (default target) (3) ->
(ClCompile target) -> 
  C:\projects\symengine-py-l1jmr\symengine\lib\symengine_wrapper.cpp(16370): error C2679: binary '=': no operator found which takes a right-hand operand of type 'SymEngine::RCP<const SymEngine::SeriesCoeffInterface>' (or there is no acceptable conversion) [C:\projects\symengine-py-l1jmr\symengine\lib\symengine_wrapper.vcxproj]
```

**Comment by certik** [comment]
Ah ok, the Travis doesn't even test the Python wrappers....

**Comment by certik** [comment]
I pushed in a temporary workaround.

**Comment by certik** [comment]
Hopefully this will install it and test it on Travis. There are some test failures, which I will tackle once it installs.

**Comment by isuruf** [comment]
@certik, you can use @rwst's patch in #44

**Comment by certik** [comment]
I will. I first want to make sure that all tests pass.

**Comment by certik** [comment]
I am testing @rwst's patch in #45.

**Comment by certik** [comment]
Closing in favor of #45.

**Pull request closed without merging**
