### PR TITLE
Proper broadcasting in Lambdify

### PR DESCRIPTION
**Pull request by bjodah**
This was an oversight by me in the original implementation.

### CODE REVIEW

**Comment by certik** [comment]
Is the appveyor failure caused by this PR?

**Comment by bjodah** [comment]
Doesn't look like it (only one failed). Can it be restarted?

**Comment by isuruf** [comment]
It seems to be related to symengine/symengine#1042

**Comment by certik** [comment]
@bjodah yes, the failure seems unrelated. I merged your PR. Thanks!

**Pull request merged**
