### PR TITLE
Update SymEngine and fix build issues

### PR DESCRIPTION
**Pull request by isuruf**
- [x] Remove running of tests in main repo's script

### CODE REVIEW

**Comment by isuruf** [comment]
Depends on symengine/symengine#782

**Comment by certik** [comment]
The changes look good, +1 if tests pass. You should probably update the hash to the latest master.

**Comment by certik** [comment]
All tests pass, except the Sage ones, that it can't find GMP.

**Comment by certik** [comment]
I think we need to set `-DCMAKE_PREFIX_PATH` in setup.py to point to `$SAGE_LOCAL`, then it should find it. Do you know a best place to do this in the `setup.py`? We should just add it on a command line to `setup.py` only when Sage is used.

**Comment by isuruf** [comment]
@certik, sage issue is because of the new sage archive's naming extracted folder name is different. It's `SageMath` now. I fixed this in another branch, but there seems to be a problem with sage's gcc. Let me get back to you after checking

**Comment by certik** [comment]
I think they use gcc 4.9.2 or so. If there are any compilation issues, then we need to fix them.

**Comment by certik** [comment]
But why cannot we use the old version of Sage for this PR that worked? We can port to new Sage in a new PR.

**Comment by isuruf** [comment]
Old sage version are not available anymore in the link. Maybe they are archived somewhere

**Comment by certik** [comment]
I can't find it either. That's terrible.

**Comment by certik** [comment]
How is it that this line https://github.com/symengine/symengine.py/blob/9d23ef72b83f93f46bba8e57ed33f0bd78d8dc0a/.travis.yml#L103 didn't fail the build when the script exited with an error?

**Comment by certik** [comment]
We should probably call it without the `source`.

**Comment by isuruf** [comment]
Because `set -e` isn't added to the top of `install_travis.sh`. `source` has to be used because the script is setting up the environment.

**Comment by certik** [comment]
I tried to fix it in #41, but I think there is an issue with setting `set -e` and sourcing it, because then it propagates into the parent shell and actually makes Travis fail. So the right solution is to install things as a regular script with `set -e`. And then just have a tiny script that sets up environment, and that one will be sourced.

**Comment by isuruf** [comment]
You can also do `set +e` at the end

**Comment by certik** [comment]
Except when it fails, then `set +e` will never be executed. But then I guess it will fail anyway, so maybe that's ok.

**Comment by certik** [comment]
Set LD_LIBRARY_PATH to $SAGE_LOCAL. That should fix it.

**Comment by certik** [comment]
@isuruf let's get the Sage stuff out of this PR, and merge #42 which restores the old Sage version and all tests pass there. In this PR let's just update the SymEngine and make sure everything passes.

We can then update Sage in a new PR.

**Comment by certik** [comment]
I like the changes up to 95d4aa0, did anything fail at this point? Let's fiddle with Travis in another PR, as we talked, we have to be a bit more careful here.

**Comment by certik** [comment]
Closing in favor of #45.

**Pull request closed without merging**
