### PR TITLE
Fix DenseMatrix.atoms

### LINKED ISSUE #190: SymPy test failures: AttributeError: 'list' object has no attribute 'atoms'
_From @ylemkimon on September 27, 2017 6:17_

Following tests fail on SymPy with SymEngine:
```
________________________________________________________________________________
___ sympy/physics/mechanics/tests/test_functions.py:test_find_dynamicsymbols ___
  File "/home/travis/build/sympy/sympy/sympy/physics/mechanics/tests/test_functions.py", line 166, in test_find_dynamicsymbols
    assert find_dynamicsymbols(expr) == sol
  File "sympy/physics/mechanics/functions.py", line 425, in find_dynamicsymbols
    return set([i for i in expression.atoms(AppliedUndef, Derivative) if
  File "symengine_wrapper.pyx", line 3568, in symengine.lib.symengine_wrapper.DenseMatrixBase.atoms
AttributeError: 'list' object has no attribute 'atoms'
________________________________________________________________________________
___________ sympy/physics/mechanics/tests/test_kane.py:test_one_dof ____________
  File "/home/travis/build/sympy/sympy/sympy/physics/mechanics/tests/test_kane.py", line 42, in test_one_dof
    assert (KM.linearize(A_and_B=True, )[0] == Matrix([[0, 1], [-k/m, -c/m]]))
  File "sympy/physics/mechanics/kane.py", line 498, in linearize
    linearizer = self.to_linearizer()
  File "sympy/physics/mechanics/kane.py", line 453, in to_linearizer
    self._k_ku, self._f_k, self._k_dnh, self._f_dnh, self._k_d]):
  File "sympy/physics/mechanics/kane.py", line 452, in <genexpr>
    if any(find_dynamicsymbols(i, sym_list) for i in [self._k_kqdot,
  File "sympy/physics/mechanics/functions.py", line 425, in find_dynamicsymbols
    return set([i for i in expression.atoms(AppliedUndef, Derivative) if
  File "symengine_wrapper.pyx", line 3568, in symengine.lib.symengine_wrapper.DenseMatrixBase.atoms
AttributeError: 'list' object has no attribute 'atoms'
________________________________________________________________________________
_________ sympy/physics/mechanics/tests/test_kane.py:test_rolling_disc _________
  File "/home/travis/build/sympy/sympy/sympy/physics/mechanics/tests/test_kane.py", line 184, in test_rolling_disc
    A = KM.linearize(A_and_B=True)[0]
  File "sympy/physics/mechanics/kane.py", line 498, in linearize
    linearizer = self.to_linearizer()
  File "sympy/physics/mechanics/kane.py", line 453, in to_linearizer
    self._k_ku, self._f_k, self._k_dnh, self._f_dnh, self._k_d]):
  File "sympy/physics/mechanics/kane.py", line 452, in <genexpr>
    if any(find_dynamicsymbols(i, sym_list) for i in [self._k_kqdot,
  File "sympy/physics/mechanics/functions.py", line 425, in find_dynamicsymbols
    return set([i for i in expression.atoms(AppliedUndef, Derivative) if
  File "symengine_wrapper.pyx", line 3568, in symengine.lib.symengine_wrapper.DenseMatrixBase.atoms
AttributeError: 'list' object has no attribute 'atoms'
________________________________________________________________________________
 sympy/physics/mechanics/tests/test_linearize.py:test_linearize_pendulum_kane_minimal 
  File "/home/travis/build/sympy/sympy/sympy/physics/mechanics/tests/test_linearize.py", line 170, in test_linearize_pendulum_kane_minimal
    A, B, inp_vec = KM.linearize(A_and_B=True, simplify=True)
  File "sympy/physics/mechanics/kane.py", line 498, in linearize
    linearizer = self.to_linearizer()
  File "sympy/physics/mechanics/kane.py", line 453, in to_linearizer
    self._k_ku, self._f_k, self._k_dnh, self._f_dnh, self._k_d]):
  File "sympy/physics/mechanics/kane.py", line 452, in <genexpr>
    if any(find_dynamicsymbols(i, sym_list) for i in [self._k_kqdot,
  File "sympy/physics/mechanics/functions.py", line 425, in find_dynamicsymbols
    return set([i for i in expression.atoms(AppliedUndef, Derivative) if
  File "symengine_wrapper.pyx", line 3568, in symengine.lib.symengine_wrapper.DenseMatrixBase.atoms
AttributeError: 'list' object has no attribute 'atoms'
________________________________________________________________________________
 sympy/physics/mechanics/tests/test_linearize.py:test_linearize_pendulum_kane_nonminimal 
  File "/home/travis/build/sympy/sympy/sympy/physics/mechanics/tests/test_linearize.py", line 236, in test_linearize_pendulum_kane_nonminimal
    simplify=True)
  File "sympy/physics/mechanics/kane.py", line 498, in linearize
    linearizer = self.to_linearizer()
  File "sympy/physics/mechanics/kane.py", line 453, in to_linearizer
    self._k_ku, self._f_k, self._k_dnh, self._f_dnh, self._k_d]):
  File "sympy/physics/mechanics/kane.py", line 452, in <genexpr>
    if any(find_dynamicsymbols(i, sym_list) for i in [self._k_kqdot,
  File "sympy/physics/mechanics/functions.py", line 425, in find_dynamicsymbols
    return set([i for i in expression.atoms(AppliedUndef, Derivative) if
  File "symengine_wrapper.pyx", line 3568, in symengine.lib.symengine_wrapper.DenseMatrixBase.atoms
AttributeError: 'list' object has no attribute 'atoms'
________________________________________________________________________________
 sympy/physics/mechanics/tests/test_linearize.py:test_linearize_pendulum_lagrange_minimal 
  File "/home/travis/build/sympy/sympy/sympy/physics/mechanics/tests/test_linearize.py", line 267, in test_linearize_pendulum_lagrange_minimal
    A, B, inp_vec = LM.linearize([q1], [q1d], A_and_B=True)
  File "sympy/physics/mechanics/lagrange.py", line 373, in linearize
    linearizer = self.to_linearizer(q_ind, qd_ind, q_dep, qd_dep)
  File "sympy/physics/mechanics/lagrange.py", line 336, in to_linearizer
    r = list(find_dynamicsymbols(f_3, insyms))
  File "sympy/physics/mechanics/functions.py", line 425, in find_dynamicsymbols
    return set([i for i in expression.atoms(AppliedUndef, Derivative) if
  File "symengine_wrapper.pyx", line 3568, in symengine.lib.symengine_wrapper.DenseMatrixBase.atoms
AttributeError: 'list' object has no attribute 'atoms'
________________________________________________________________________________
 sympy/physics/mechanics/tests/test_linearize.py:test_linearize_pendulum_lagrange_nonminimal 
  File "/home/travis/build/sympy/sympy/sympy/physics/mechanics/tests/test_linearize.py", line 301, in test_linearize_pendulum_lagrange_nonminimal
    op_point=op_point, A_and_B=True)
  File "sympy/physics/mechanics/lagrange.py", line 373, in linearize
    linearizer = self.to_linearizer(q_ind, qd_ind, q_dep, qd_dep)
  File "sympy/physics/mechanics/lagrange.py", line 336, in to_linearizer
    r = list(find_dynamicsymbols(f_3, insyms))
  File "sympy/physics/mechanics/functions.py", line 425, in find_dynamicsymbols
    return set([i for i in expression.atoms(AppliedUndef, Derivative) if
  File "symengine_wrapper.pyx", line 3568, in symengine.lib.symengine_wrapper.DenseMatrixBase.atoms
AttributeError: 'list' object has no attribute 'atoms'
________________________________________________________________________________
 sympy/physics/mechanics/tests/test_linearize.py:test_linearize_rolling_disc_lagrange 
  File "/home/travis/build/sympy/sympy/sympy/physics/mechanics/tests/test_linearize.py", line 332, in test_linearize_rolling_disc_lagrange
    A = l.linearize(q_ind=q, qd_ind=qd, op_point=op_point, A_and_B=True)[0]
  File "sympy/physics/mechanics/lagrange.py", line 373, in linearize
    linearizer = self.to_linearizer(q_ind, qd_ind, q_dep, qd_dep)
  File "sympy/physics/mechanics/lagrange.py", line 336, in to_linearizer
    r = list(find_dynamicsymbols(f_3, insyms))
  File "sympy/physics/mechanics/functions.py", line 425, in find_dynamicsymbols
    return set([i for i in expression.atoms(AppliedUndef, Derivative) if
  File "symengine_wrapper.pyx", line 3568, in symengine.lib.symengine_wrapper.DenseMatrixBase.atoms
AttributeError: 'list' object has no attribute 'atoms'
===== tests finished: 42 passed, 2 skipped, 8 exceptions, in 28.84 seconds =====
DO *NOT* COMMIT!
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
Exception: Tests failed
```
since version
```
    python-symengine:   0.3.0.56.g3fd1e481-py27_0     symengine/label/dev
    symengine:          0.3.0.213.ga2a839b5-3         symengine/label/dev
```

_Copied from original issue: symengine/symengine#1331_

### PR DESCRIPTION
**Pull request by isuruf**
Fixes #190

### CODE REVIEW

**Comment by ShikharJ** [comment]
Looks good. Though any idea why this issue crept up after updating the binaries?

**Comment by isuruf** [comment]
It was because `tolist` was updated recently.

**Comment by certik** [comment]
+1

**Comment by certik** [comment]
There seems to be a link failure in MinGW:
```
[100%] Linking CXX shared library symengine_wrapper.pyd
CMakeFiles\symengine_wrapper.dir/objects.a(symengine_wrapper.cpp.obj): In function `__Pyx_Coroutine_Send':
C:/projects/symengine-py-l1jmr/symengine/lib/symengine_wrapper.cpp:174198: undefined reference to `_PyGen_Send'
C:/projects/symengine-py-l1jmr/symengine/lib/symengine_wrapper.cpp:174203: undefined reference to `_PyGen_Send'
CMakeFiles\symengine_wrapper.dir/objects.a(symengine_wrapper.cpp.obj): In function `__Pyx_Generator_Next':
C:/projects/symengine-py-l1jmr/symengine/lib/symengine_wrapper.cpp:174287: undefined reference to `_PyGen_Send'
collect2.exe: error: ld returned 1 exit status
symengine\lib\CMakeFiles\symengine_wrapper.dir\build.make:133: recipe for target 'symengine/lib/symengine_wrapper.pyd' failed
```
But that is probably unrelated to this PR? Perhaps a different Cython version was used?

**Comment by isuruf** [comment]
Probably a change to python version in appveyor. We are using a patched version of `libpython`, so that MinGW works with it. Since we are not replacing other components, there might be issues with this.

**Comment by ShikharJ** [comment]
Thanks.

**Pull request merged**
