### PR TITLE
Fix GHA

### PR DESCRIPTION
**Pull request by HaoZeke**
Sorry about the broken build. Surprisingly [wasn't showing up before](https://github.com/HaoZeke/symengine.py/runs/1818144467?check_suite_focus=true) in-spite of literally zero changes to the workflow.

image

- [a1dd147 passes](https://github.com/HaoZeke/symengine.py/actions/runs/532079838)
- [a6cda09 fails](https://github.com/HaoZeke/symengine.py/actions/runs/566379824)

Probably has something to do with changes over at `symengine/symengine`.

### CODE REVIEW

**Comment by isuruf** [comment]
We should fix symengine itself instead of disabling flint when building docs.

**Comment by HaoZeke** [comment]
That's true, but there aren't any docstrings which are affected by the presence (or lack) of `flint` at the moment so it might be a good idea to have the bindings up and then keep an issue open on `symengine/symengine`

**Comment by HaoZeke** [comment]
Sorry. I should just change the version we use. Symengine itself doesn't have this problem.

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
