### PR TITLE
Use symengine's new interface for lambda double

### PR DESCRIPTION
**Pull request by isuruf**
Depends on symengine/symengine#1094

### CODE REVIEW

**Comment by isuruf** [comment]
Ready for review. LLVMDoubleVisitor should be another PR.

**Comment by bjodah** [comment]
Looks great!

**Comment by isuruf** [comment]
Tests fail with
`symengine.tests.test_lambdify.test_cse_list_input ... bin/test_travis.sh: line 19: 22264 Segmentation fault: 11  nosetests -v`
I'll try to reproduce this locally

**Comment by bjodah** [comment]
Do you think #105 might be related?

**Comment by isuruf** [comment]
I just pushed a fix, let's see.

**Comment by sighingnow** [comment]
Hi @isuruf I'm afraid that simplify expressions before sending to sympy can't fix #105. In the implementation of sympy's `cse` function, [line 530 of cse_main.py](https://github.com/sympy/sympy/blob/c9af43024255c81541028b6accb400cb173b2c54/sympy/simplify/cse_main.py#L530), we can see that all expressions must be instances of sympy's `Basic` class. However, we can't inherit symengine's `Basic` class from sympy's `Basic` class, as cdef classes can't inherit from normal Python classes, see [cython doc](http://cython.readthedocs.io/en/latest/src/tutorial/cdef_classes.html). So, just simplify the expressions can't fix #105.

I think the correct way to fix it is casting expression to sympy's value before sending to the `sympy.cse` function. I mean, something like this:

~~~python
    subs, new_exprs = cse([expr._sympy_() for expr in exprs])
~~~

**Comment by isuruf** [comment]
@sighingnow, `sympy`'s `sympify` call `Basic._sympy_()`. So, it's the same thing

**Comment by sighingnow** [comment]
OK, I got it. Thanks very much for your reply @isuruf .

**Comment by isuruf** [comment]
Anybody have access to a Mac?

**Comment by isuruf** [comment]
On OS X, Python=3.5 Release mode fails while Debug mode passes

**Comment by bjodah** [comment]
I have ssh access to a Mac OS X machine, never used OX X though, I will try to debug.

**Comment by bjodah** [comment]
I'm struggling on OSX,vI can't even get libsymengine ctest suite to pass, all tests fail like this:
```
Test project /Users/user/isuruf-llvm/symengine.py-llvm/symengine-cpp/build
      Start  1: test_rcp
 1/34 Test  #1: test_rcp .........................***Exception: Other  0.07 sec
...
The following tests FAILED:
	  1 - test_rcp (OTHER_FAULT)
...
```

**Comment by isuruf** [comment]
Hmm, can you try the conda package for symengine?

**Comment by bjodah** [comment]
I will, but I'm afraid I've run out of time for today. I can try again next weekend. If you want to make progress earlier I could try to provide you with an account on that box with ssh access? Just email me your public ssh key or preferred password to my gmail:  bjodah
and I'll try to set it up tomorrow.

**Comment by isuruf** [comment]
Thanks to @bjodah, I got access to a Mac and I was able to reproduce this.
Python 3.5 in Release mode with AppleClang triggers this segfault. Segfault is not there when a different Python version is used or in Debug mode or with gcc.
All the lambdify tests segfault and the segfault happens in init, before the __call__.
I'll update this thread, when I find something more.

**Comment by isuruf** [comment]
Added a fix. I'm not happy with the fix, but this is the best I could come up for now. I'll try to get a proper fix in later. Meanwhile, can somebody review the last commit , so that we can move on the LLVMDoubleVisitor?

**Comment by certik** [comment]
I think this is fine.

In the long run, I still think we should switch our Python wrappers to use the C API. Still use Cython, but just a C compiler and C API. This will speedup the compilation greatly, and get rid of all these bugs. We already have an issue for this at #91.

**Comment by certik** [comment]
+1 to merge as it is.

**Pull request merged**
