### PR TITLE
implement Basic.as_coefficient_dict(); part of #59

### PR DESCRIPTION
**Pull request by rwst**

### CODE REVIEW

**Comment by certik** [comment]
The failure on Windows seems to be genuine. We need to figure out what is causing it. Is it a bug in SymEngine itself, or the Python wrappers?

**Comment by rwst** [comment]
I'm completely Windoze-free. Can I help another way?

**Comment by isuruf** [comment]
This is probably because `hash(1) != hash(Integer(1))` in MSVC

**Comment by certik** [comment]
I see, that was it. I think we hit this before, so I don't think it's related to this PR, is it?

How should we fix it in the long term?

**Comment by certik** [comment]
Yeah, the PR looks good to me, merging.

**Pull request merged**
