### PR TITLE
Raise TypeError for bool(Booleans) except true, false

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Review by bjodah — APPROVED** [review]
Looks good. So we had an incorrect test hiding in test_eval_double2() then I suppose?

**Comment by isuruf** [comment]
> So we had an incorrect test hiding in test_eval_double2() then I suppose?

Yes, `assert lhs < rhs` is true regardless of `lhs` and `rhs` because `bool(Lt(lhs, rhs))` silently produces true.

**Review by rikardn — APPROVED** [review]
LGTM

**Comment by isuruf** [comment]
Thanks for the review

**Pull request merged**
