### PR TITLE
Cython3 support

### PR DESCRIPTION
**Pull request by isuruf**
Major change is in d4ca69fe8944548ab2758fa2b21c4409aaba4435 which is a workaround to Cython3 deprecating
the support for translation time constant conditional statements.

### CODE REVIEW

**Comment by isuruf** [comment]
cc @mgorny

**Review by thilinarmtb — APPROVED** [review]

**Comment by bjodah** [comment]
Well done on finding a workaround @isuruf. If we had unlimited time resources I guess we would come up with something else, but this looks like the simplest fix to me. :)

**Review by bjodah — APPROVED** [review]

**Comment by bjodah** [comment]
Maybe we should add a CI-job which explicitly runs with `cython>=3`?

**Comment by isuruf** [comment]
New CI uses cython3 now

**Pull request merged**
