### PR TITLE
Remove python 3.3 support

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
xref #219 
xref #235

**Comment by jcfr** [comment]
After this is integrated, I will update #219 so that we can move forward.

**Comment by certik** [comment]
I restarted the failed jobs. One error seems real: https://github.com/symengine/symengine.py/issues/239, but obviously unrelated to this PR.

**Comment by jcfr** [comment]
@isuruf Considering that the failure of the one test is unrelated, do you think we could move forward with the integration of this PR ?  Thanks

**Comment by isuruf** [comment]
Thanks for the Pr

**Pull request merged**
