### PR TITLE
Fix version mismatch of gcc and libstdc++ in appveyor

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by certik** [comment]
Looking at the error,:
```
if [%COMPILER%]==[MinGW-w64] python setup.py install build --compiler=mingw
if not [%COMPILER%]==[MSVC15] nosetests
.................................................................Command exited with code -1073741819
```
it looks like it ended up with a segfault. Didn't it?

**Comment by isuruf** [comment]
I restarted the build and it is the same. This error code is `0xc0000005` in hex and is a common error in windows. It is a AccessViolationException. I'm not sure whether it is our fault or appveyor's.

**Comment by certik** [comment]
It looks like a segfault. This is running in Release mode, right? It seems to be working in Debug mode, so that sucks. Normally we should get a nice exception if there is some dangling pointer or something.

**Comment by isuruf** [comment]
@certik, can you review?

**Comment by certik** [comment]
That looks good to me, +1.

**Comment by isuruf** [comment]
Thanks. I'm going to keep #94 open as this PR doesn't solve it.

**Pull request merged**
