### PR TITLE
exposed llvm lambdify opt_level in python api

### PR DESCRIPTION
**Pull request by ichumuh**
As requested by me in https://github.com/symengine/symengine/pull/1612#. Do you think it look good? 
@isuruf can you please merge https://github.com/isuruf/symengine/commit/ac7b9bb28cfaafffbf839be7a2a6424ecc2eaf9e as well?

### CODE REVIEW

**Comment by certik** [comment]
Would you mind adding a test for this flag please? It would go somewhere in https://github.com/symengine/symengine.py/blob/8909cff0f1087a6e743821b580531d5b02f04b74/symengine/tests/test_lambdify.py.

**Comment by ichumuh** [comment]
To do this test properly, I'd have to check if the opt_level actually works, right? The only why I can think of right now would be to compair runtimes, but that doesn't seem clean to me. Do you have a better idea? Or do I just test if it doesn't throw errors?

**Comment by certik** [comment]
I would just test that the `opt_level` can be passed in. It's our responsibility in the C++ symengine to ensure it actually works.

**Comment by ichumuh** [comment]
I currently have added `opt_level` to `LLVMDouble`, `LambdaDouble` and `_Lambdify`.
But we actually only need it for `LLVMDouble`. Would it be better to only add it to that class and to use something as default, when `Lambdify` is used?

**Comment by bjodah** [comment]
Yes, let's make sure that passing `opt_level` to LambdaDouble throws an exception.

**Comment by ichumuh** [comment]
So should `Lambdify` accept `opt_level` or not? It seems to me like `LLVMDouble` is not intended to be used directly.

**Comment by bjodah** [comment]
Have it accept **kwargs? anf if backend=="llvm" then opt_level can be popped out of kwargs (`opt_level=kwargs.pop("opt_level", 3)` and at end of __init__ we always check that kwargs is empty, and if not: raise an exception)

**Comment by isuruf** [comment]
Yes, but if the backend is `lambda`, we should check that `opt_level` is None. If the backend is `lambda` and `opt_level` is None, `opt_level=3` should be passed. If the backend is `lambda` and `opt_level` is not None, value should be passed through.

**Comment by ichumuh** [comment]
@isuruf you meant `llvm` instead of `lambda` right?

**Comment by isuruf** [comment]
Yes, @bjodah's proposal sounds better to me though.

**Comment by ichumuh** [comment]
How about this? `__init__` in `_Lambdify` accepts `kwargs` as well and I use `__cinit__` in `LambdaDouble` and `LLVMDouble` to extract needed parameters. `Lambdify` can just pass `kwargs`. This automatically gives me an error, when I use `opt_level` with backend `lambda` for example.

**Comment by bjodah** [comment]
That looks good, but perhaps the default should be higher than 0? (we should probably gather some benchmarks for LLVMDouble eventually)

We can also check that it's given a valid value:
```
if not 0<=opt_level<=3:
    raise ValueError("opt_level needs to be 0, 1, 2 or 3, got: %s" % str(opt_level))
```
(or we make sure this check is done on the C++ side)

**Comment by ichumuh** [comment]
>That looks good, but perhaps the default should be higher than 0? (we should probably gather some benchmarks for LLVMDouble eventually)

Sure, I'll make it 3 again and write some tests.

>We can also check that it's given a valid value:

I think the c++ side should do this check, maybe the range will change at some point.

**Comment by ichumuh** [comment]
> We can also check that it's given a valid value:
> 
> ```
> if not 0<=opt_level<=3:
>     raise ValueError("opt_level needs to be 0, 1, 2 or 3, got: %s" % str(opt_level))
> ```
> 
> (or we make sure this check is done on the C++ side)

It currently seems like there is only a difference between `0` and **not** `0`, all negative and positive always seem to produce the same numbers. I don't know why 3 is the default in the C++ api. Maybe it's because I'm using llvm 8.0?

**Comment by bjodah** [comment]
Maybe the cost/benefit ratio depends on the type of expression, e.g. if there many `Piecewise` objects (but it's just guesswork on my part).

I don't remember what the story was for auto-vectorization for example. But it would be nice if such optimizations were possible (in the future), but that's off topic for this PR of course. But since I'm already digressing, this gets me thinking: I don't think LLVM comes with approximate transcendentals(?), intel's compiler has such a flag:
https://software.intel.com/en-us/cpp-compiler-developer-guide-and-reference-fast-transcendentals-qfast-transcendentals
such optimizations would also be a pretty nice option once/if llvm supports them.

**Comment by ichumuh** [comment]
How do I actually run the tests? When I'm doing `py.test -v symengine/tests/test_*.py` I get 
```
ImportError while importing test module '/home/stelter/my_symengine/symengine.py/symengine/tests/test_var.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
symengine/__init__.py:1: in <module>
    from .lib.symengine_wrapper import (
E   ImportError: No module named symengine_wrapper
```
While inside of this folder I also can't import symengine, it throws the same error.
When I'm in a different folder, symengine works though.

**Comment by ichumuh** [comment]
Nvm, the tests work when I'm in `/usr/local/lib/python2.7/dist-packages` and do `py.test -v symengine/tests/test_*.py`

**Comment by ichumuh** [comment]
Are these tests sufficient?

**Comment by bjodah** [comment]
+1 from me.
And thank you for working on this!

**Pull request merged**
