### PR TITLE
fix of missing order-parameter in LambdifyCSE

### PR DESCRIPTION
**Pull request by raphaelquast**
since i really wanted to use this function, i gave it a quick try if i find something suspicious...

- the newly introduced order-argument was missing in two calls of Lambify()
which consequently results in an error once it is changed to a non-default value

- this finally fixes the remaining parts of the issue #174

### CODE REVIEW

**Comment by isuruf** [comment]
Looks good to me. Can you add a test for this?

**Comment by raphaelquast** [comment]
the comments i already added to the referenced issues could be used as quick tests...
https://github.com/symengine/symengine.py/issues/174#issuecomment-339299730  or https://github.com/symengine/symengine/issues/1350#issuecomment-343095793

**Comment by isuruf** [comment]
This PR is not needed because of https://github.com/symengine/symengine.py/pull/209

**Comment by isuruf** [comment]
@raphaelquast, can you check the latest master to see if there's any issue?

**Comment by raphaelquast** [comment]
@isuruf yes i can, but i'll need another dev-version bumped for that...

**Pull request closed without merging**
