### PR TITLE
SymPy compat

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
appveyor failure is unrelated

**Comment by isuruf** [comment]
@certik, ping

**Comment by certik** [comment]
We can merge it, if you want to try it out. 

What is the motivation though? How is it different to our other Python wrappers?

**Comment by isuruf** [comment]
This was what @asmeurer and I discussed at sprints.

Main motivations are in the unit tests.

1. We can use `Add` as a constructor and type.
```
def test_Add():
    x, y = symbols("x y")
    i = Add(x, x)
    assert isinstance(i, Mul)
    i = Add(x, y)
    assert isinstance(i, Add)
    assert isinstance(i, Basic)
```

2. `Integer`s are `Rational`s
```
def test_Integer():
    i = Integer(5)
    assert isinstance(i, Integer)
    assert isinstance(i, Rational)
    assert isinstance(i, Basic)
```

**Comment by isuruf** [comment]
Updated motivations

**Comment by certik** [comment]
I see. Yes, we can try this out and see how it goes.

**Pull request merged**
