### PR TITLE
Add Expr Class

### PR DESCRIPTION
**Pull request by ShikharJ**

### CODE REVIEW

**Comment by isuruf** [comment]
There are more classes like `class Symbol(Basic)` that needs to be fixed.

**Comment by isuruf** [comment]
Also export `Expr` in the main module.

**Comment by ShikharJ** [comment]
Ping @isuruf

**Comment by isuruf** [comment]
Can you search for (Basic) and fix those please? For eg. class Boolean (Basic) needs to be fixed.

**Comment by isuruf** [comment]
Thanks

**Comment by isuruf** [comment]
@ShikharJ, please send a PR to https://github.com/symengine/python-symengine-feedstock so that this change could be used in sympy

**Comment by ShikharJ** [comment]
@isuruf Actually, I was waiting up till the time I had pushed in all the PRs to `SymPy` (which should be done by tomorrow). So that I'll won't have to send PRs repeatedly to `python-symengine-feedstock` in order to make the minor changes (that might come up later, through discussions or otherwise) in `SymEngine.py` available. If its urgent, then please let me know.

**Pull request merged**
