### PR TITLE
Prepare for v0.2.0 release

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
After this PR is merged, I'll tag master. Once tagged, conda packages and pypi upload will happen automatically. I'll upload to launchpad after that.

**Comment by isuruf** [comment]
@certik, ping

**Comment by isuruf** [comment]
This PR should be merged only after #99.

**Comment by isuruf** [comment]
Thanks for the review @rwst

**Comment by certik** [comment]
+1, thanks @isuruf and @rwst .

**Pull request merged**
